### ISSUE TITLE
Modification Date of Previously Packaged Download always (0)

### ISSUE THREAD

**Issue by mmcphail** [neographophobic/autoMunkiImporter#4]
Every time the script runs all packages re-download.  The entry in the log file is:

Fri Jan 24 05:00:19 2014 Attempting to read data plist /Library/Application Support/autoMunkiImporter/Chrome.plist
Fri Jan 24 05:00:19 2014 App Name: Chrome
Fri Jan 24 05:00:19 2014 Processing Type: static
Fri Jan 24 05:00:19 2014 Determining URL of download...
Fri Jan 24 05:00:19 2014 Initial URL: https://dl.google.com/chrome/mac/stable/GGRM/googlechrome.dmg
Fri Jan 24 05:00:20 2014 Final URL: https://dl.google.com/chrome/mac/stable/GGRM/googlechrome.dmg
Fri Jan 24 05:00:20 2014 Determine if file has changed since we last processed it...
Fri Jan 24 05:00:20 2014 Modification Date of Download:                     Tue, 14 Jan 2014 11:54:00 CST (1389722040)
Fri Jan 24 05:00:20 2014 Modification Date of Previously Packaged Download: Wed, 31 Dec 1969 18:00:00 CST (0)

The modifiedDate entry in the Status plist is correct, but it always reads into the script as (0).

**Comment by neographophobic** [comment]
What version of OS X are you running the script on?

On 25 Jan 2014, at 3:49 am, mmcphail <notifications@github.com<mailto:notifications@github.com>> wrote:

Every time the script runs all packages re-download. The entry in the log file is:

Fri Jan 24 05:00:19 2014 Attempting to read data plist /Library/Application Support/autoMunkiImporter/Chrome.plist
Fri Jan 24 05:00:19 2014 App Name: Chrome
Fri Jan 24 05:00:19 2014 Processing Type: static
Fri Jan 24 05:00:19 2014 Determining URL of download...
Fri Jan 24 05:00:19 2014 Initial URL: https://dl.google.com/chrome/mac/stable/GGRM/googlechrome.dmg
Fri Jan 24 05:00:20 2014 Final URL: https://dl.google.com/chrome/mac/stable/GGRM/googlechrome.dmg
Fri Jan 24 05:00:20 2014 Determine if file has changed since we last processed it...
Fri Jan 24 05:00:20 2014 Modification Date of Download: Tue, 14 Jan 2014 11:54:00 CST (1389722040)
Fri Jan 24 05:00:20 2014 Modification Date of Previously Packaged Download: Wed, 31 Dec 1969 18:00:00 CST (0)

The modifiedDate entry in the Status plist is correct, but it always reads into the script as (0).

**Comment by mmcphail** [comment]
Installed on Mountain Lion, have upgraded to Mavericks with same issue.

**Comment by neographophobic** [comment]
I wonder if it's a permissions issue on the file /Library/Application Support/autoMunkiImporter/Chrome.plist or it's parent directories?

You mention the modifiedDate in the status file. Is it being set in /Library/Application Support/autoMunkiImporter/Chrome.plist as well? Ideally you should see two entries like the following:-
<key>modifiedDate</key>
<date>2014-01-27T17:54:00Z</date>
<key>modifiedDateCorrospoindingVersion</key>
<string>32.0.1700.102</string>

I suspect that what is happening is that autoMunkiImporter can't update that plist to say it's downloaded an update, and without those details, it thinks there is a new version and re-imports it. The most likely cause is permissions. Check that the process running autoMunkiImporter can modify the plist and try it again.

I hope this helps.

On 29 Jan 2014, at 5:50 am, mmcphail <notifications@github.com<mailto:notifications@github.com>> wrote:

Installed on Mountain Lion, have upgraded to Mavericks with same issue.

**Comment by mmcphail** [comment]
Changing permissions didn't make any difference.  Looking at the .plist file, the both of the entries are there and the same as what you provided.  It just doesn't seem to read the entries when parsing the file.

**Comment by neographophobic** [comment]
I'm closing old issues. I suggest that you look at [AutoPkg](https://github.com/autopkg/autopkg) for any future requirements for automating Munki.
